### ISSUE TITLE
Rising Night related guild quests not currently possible

### ISSUE THREAD

**Issue by Borfie** [Kondoorsoft/WQ2-issues#15]
### Describe the bug

Guild Quests that require you to kill a certain amount of enemies currently include the Rising Night faction, which does not show up anywhere after liberating both regions

### Steps To Reproduce

Happens randomly when given a quest

### Game Settings

- [ ] Single-player
- [ ] Split-screen

### Graphics Settings

- [ ] Full-screen
- [ ] Windowed
- [ ] FSR 1 enabled
- [ ] FSR 2 enabled
- [ ] V-Sync enabled

**Comment by jeremyd4500** [comment]
@kondoorsoft-trent For the purposes of the demo, the easier solution here is to just remove the rising night enemies as a possible choice when these quests are generated. But alternatively, we could just place some rising night soldiers around the liberated versions of both regions. What are your thoughts?
