### ISSUE TITLE
Enemies die standing

### ISSUE THREAD

**Issue by Patantasma** [Kondoorsoft/WQ2-issues#3]
When you play as a mage, when you kill enemies at a certain distance, they will die standing and may not drop loot. This only really happens when you're either too far for them to aggro and their tags don't show up (where this tends to happen the most), or when are able to aggro and attack (like with enemies mages), but the distance is far enough where this can trigger.

**Example 1**: Can see their tags, but distance was far enough where he died standing
![20241001212922_1](https://github.com/user-attachments/assets/fd5324f9-29f8-41df-85c5-03609ec3717d)
![20241001212929_1](https://github.com/user-attachments/assets/b75adae7-2b6d-4437-858f-5413db90ac61)

**Example 2**: Too far to see tags, and he died standing here too
![20241001214839_1](https://github.com/user-attachments/assets/30c4600e-97e7-4c77-b23a-5a18eaa930d8)
![20241001221749_1](https://github.com/user-attachments/assets/f83c5ed2-141b-4ea9-b7f4-6f138b025aac)
(Here he is just chilling-)

**Comment by jeremyd4500** [comment]
Thanks for reporting this! We'll work on this and use this thread to update our progress

**Comment by jeremyd4500** [comment]
Sorry for the delay! But I'm happy to report that the fix for this will be included in the next release
