### ISSUE TITLE
It is possible to jump on water

### ISSUE THREAD

**Issue by Simon-NTI** [Kondoorsoft/WQ2-issues#30]
### Describe the bug

Jumping just before entering the swim animation will result in the player jumping on the water

### Steps To Reproduce

Read above

### Expected behavior

The player should not be able to jump on the water, and should instead start swimming.

### Videos

[Video](https://drive.google.com/file/d/1xz_St-49ARSYWM3g4iYoGOjh0hQTQTu6/view?usp=sharing)

### Game Settings

- [x] Single-player
- [ ] Split-screen

### Graphics Settings

- [x] Full-screen
- [ ] Windowed
- [ ] FSR 1 enabled
- [x] FSR 2 enabled
- [ ] V-Sync enabled

### OS & OS Version

Windows 10

### Device Played On

PC

### PC Hardware

16GB RAM
Ryzen 5 3600
NVIDIA GeForce RTX 2060
1920 x 1080 144hz monitor

### Peripherals

Keyboard + mouse

### Additional Information

Binding jump to the scroll wheel will make this easier to perform

**Comment by jeremyd4500** [comment]
Thank you for reporting this! Sorry it's taken us so long to get around to it. But I'm happy to report that the fix for this will be included in the next release!
