### ISSUE TITLE
Hold To Attack

### ISSUE THREAD

**Issue by Borfie** [Kondoorsoft/WQ2-issues#7]
### Is your feature request related to a problem? Please describe

Constant attacking currently consists of mashing the attack button

### Describe your idea
Holding the attack button should swing/shoot at the same cooldown rate as it does when mashing

### Describe the value this feature would add to the game

Less strain when fighting

### Additional Information

None

**Comment by jeremyd4500** [comment]
Thanks for submitting this issue! After some deliberation, we've decided that holding an input to continuously attack is not a feature we want to have.
